import cv2
# img = cv2.imread("C://Users/Victus/Documents/Images/black.jpg")
img1 = cv2.imread("C://Users/Victus/Documents/Images/bird.jpg")
img2 = cv2.imread("C://Users/Victus/Documents/Images/flower.jpg")
img1 = cv2.resize(img1,(300,300))
img2 = cv2.resize(img2,(300,300))
img_bitwisenot1 = cv2.bitwise_not(img1)
img_bitwisenot2 = cv2.bitwise_not(img2)
img_bitwiseor = cv2.bitwise_or(img1,img2)
img_bitwiseand = cv2.bitwise_and(img1,img2)
cv2.imshow("Original Image 1", img1)
cv2.imshow("Original Image 2", img2)
cv2.imshow('Bitwise Not(flip) 1',img_bitwisenot1)
cv2.imshow('Bitwise Not(flip) 2',img_bitwisenot2)
cv2.imshow('Bitwise Or',img_bitwiseor)
cv2.imshow('Bitwise And',img_bitwiseand)
# cv2.imshow("Image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
