import cv2
img1 = cv2.imread("C://Users/Victus/Documents/Images/flower.jpg")
img1 = cv2.resize(img1,(500,500))
img_blur = cv2.blur(img1,(9,9))
img_gaussian_blur = cv2.GaussianBlur(img1,(9,9),5)
img_median_blur = cv2.medianBlur(img1,15)
img2 = cv2.hconcat([img1,img_blur])
img3 = cv2.hconcat([img1,img_gaussian_blur])
img4 = cv2.hconcat([img1,img_median_blur])
# cv2.imshow('Original and Blurred Image', img2)
# cv2.imshow('Original and Gaussian BLurred Image', img3)
cv2.imshow('Original and Median Blurred Image',img4)
cv2.waitKey(0)
cv2.destroyAllWindows()